In [ ]:
# Importing the python libraries
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
import pycountry
import pandas as pd
 # loading the dataset
customer_transaction_data = pd.read_csv(r"C:/Users/user/Downloads/Fraudulent_Transaction_Detection_for_Finlora_Company/Finlora_Dataset/FinLora_Customer_Transaction_Dataset.csv")


In [ ]:
# checking for number of rows and columns
customer_transaction_data.shape

# checking for all the columns in the dataset
customer_transaction_data.columns


Index(['transaction_id', 'customer_id', 'timestamp', 'home_country',
       'source_currency', 'dest_currency', 'channel', 'amount_src',
       'amount_usd', 'fee', 'exchange_rate_src_to_dest', 'device_id',
       'new_device', 'ip_address', 'ip_country', 'location_mismatch',
       'ip_risk_score', 'kyc_tier', 'account_age_days', 'device_trust_score',
       'chargeback_history_count', 'risk_score_internal', 'txn_velocity_1h',
       'txn_velocity_24h', 'corridor_risk', 'is_fraud'],
      dtype='object')

In [ ]:
# checking for missing data
customer_transaction_data.isnull().sum()


transaction_id                 0
customer_id                    0
timestamp                     29
home_country                   0
source_currency                0
dest_currency                  0
channel                        0
amount_src                     0
amount_usd                   305
fee                          295
exchange_rate_src_to_dest      0
device_id                      0
new_device                     0
ip_address                   305
ip_country                   301
location_mismatch              0
ip_risk_score                  0
kyc_tier                     300
account_age_days               0
device_trust_score           295
chargeback_history_count       0
risk_score_internal            0
txn_velocity_1h                0
txn_velocity_24h               0
corridor_risk                  0
is_fraud                       0
dtype: int64

In [ ]:
# checking the dataset information
customer_transaction_data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11400 entries, 0 to 11399
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   transaction_id             11400 non-null  object 
 1   customer_id                11400 non-null  object 
 2   timestamp                  11371 non-null  object 
 3   home_country               11400 non-null  object 
 4   source_currency            11400 non-null  object 
 5   dest_currency              11400 non-null  object 
 6   channel                    11400 non-null  object 
 7   amount_src                 11400 non-null  object 
 8   amount_usd                 11095 non-null  float64
 9   fee                        11105 non-null  float64
 10  exchange_rate_src_to_dest  11400 non-null  float64
 11  device_id                  11400 non-null  object 
 12  new_device                 11400 non-null  bool   
 13  ip_address                 11095 non-null  obj

In [ ]:
customer_transaction_data['amount_src'].value_counts(dropna=False).head(20)


amount_src
100.0     15
102.29     5
115.29     4
71.78      4
102.37     4
105.2      4
119.15     4
250.19     4
261.23     4
94.34      4
54.74      4
167.16     4
58.93      4
121.3      4
82.25      4
128.93     4
144.29     4
99.23      3
295.6      3
160.06     3
Name: count, dtype: int64

In [ ]:
customer_transaction_data.groupby("is_fraud")["amount_src"].describe()


,count,unique,top,freq
is_fraud,,,,
0,10403,8947,102.29,5
1,997,981,100.0,15


In [ ]:
## SUMMARY / OBSERVATIONS
## - The dataset contains 11,400 rows and 26 columns, covering transaction logs, customer profiles, device metadata, and fraud‑risk indicators.

##- All field names follow standard variable naming conventions, ensuring consistency and readability across the dataset.

##- An initial inspection revealed data type inconsistencies:
 #-  timestamp  is stored as an object instead of a proper datetime format.
 #-  amount_src  is stored as an object instead of a numeric type (float).
 #-  These issues must be corrected during preprocessing to enable accurate time‑based and numerical analysis.

##- A review of missing values shows several variables with incomplete records:
  #- timestamp   → 29 missing values  
  #- amount_usd  → 305 missing values  
  #- ip_address  → 305 missing values  
  #- fee  → 295 missing values  
  #- device_trust_score  → 295 missing values  
  #- ip_country → 301 missing values  
  #- kyc_tier → 300 missing values  
## These missing values require appropriate cleaning strategies such as imputation or removal depending on the variable type.

##- The target variable is_fraud  is highly imbalanced, with approximately 91% legitimate transactions and 9% fraudulent ones.  
##- This imbalance may cause machine learning models to favor predicting legitimate transactions while failing to detect fraud.  
##- Relying solely on accuracy would be misleading.

##- To mitigate this issue, techniques such as:
##- 1.Resampling methods  (SMOTE, oversampling, undersampling)  
##- 2.class weighting 
#-  3.Appropriate evaluation metrics (Precision, Recall, F1‑Score, ROC‑AUC)  
#    should be used to ensure the model effectively identifies fraudulent transactions.

# Checking for label imbalance
customer_transaction_data['is_fraud'].value_counts(normalize=True).reset_index()




,is_fraud,proportion
0,0,0.912544
1,1,0.087456


In [ ]:
###  Class Imbalance Summary

#  The distribution of the target variable `is_fraud`  shows a significant imbalance:

#- 91.25%  → Legitimate transactions (class 0)  
#- 8.75% → Fraudulent transactions (class 1)  

# This means the dataset contains far more normal transactions than fraud cases, which can cause machine learning models to become biased toward predicting legitimate transactions.


In [ ]:
##   DATA CLEANING AND PREPARATION

### 1. Converting Incorrect Data Types

## To ensure accurate analysis and modeling, several columns require conversion to their correct data types.

# converting data types of timestamp to datetime
customer_transaction_data['timestamp'] = pd.to_datetime(customer_transaction_data['timestamp'], errors='coerce')



In [ ]:
# Confirming Updated Data Types-After performing the conversions, i have to  inspect the dataset again to verify that the changes were applied correctly.

In [ ]:
customer_transaction_data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11400 entries, 0 to 11399
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype              
---  ------                     --------------  -----              
 0   transaction_id             11400 non-null  object             
 1   customer_id                11400 non-null  object             
 2   timestamp                  11339 non-null  datetime64[ns, UTC]
 3   home_country               11400 non-null  object             
 4   source_currency            11400 non-null  object             
 5   dest_currency              11400 non-null  object             
 6   channel                    11400 non-null  object             
 7   amount_src                 11400 non-null  object             
 8   amount_usd                 11095 non-null  float64            
 9   fee                        11105 non-null  float64            
 10  exchange_rate_src_to_dest  11400 non-null  float64            
 11  de

In [ ]:
customer_transaction_data['amount_src'] = pd.to_numeric(customer_transaction_data['amount_src'], errors='coerce')


###  Converting `amount_src` to Numeric

The `amount_src` column contains transaction amounts in the source currency.  
To ensure proper numerical operations (aggregation, scaling, modeling), i convert it to a numeric data type.

Any non-numeric values will be coerced into `NaN` for later handling.

customer_transaction_data['amount_src'] = pd.to_numeric(customer_transaction_data['amount_src'], errors='coerce')


###  Data Preprocessing Notes

During the data preprocessing stage, the `timestamp` and `amount_src` variables were converted to appropriate data types using `pd.to_datetime()` and `pd.to_numeric()` with the `errors='coerce'` argument. This conversion ensures that both fields can be used reliably for downstream analysis and modeling.

However, applying these conversions revealed additional invalid or improperly formatted entries that could not be parsed correctly. As a result, the number of missing values increased:

- timestamp: missing values increased from 29 → 61
- amount_src: missing values increased from  0 → 4

These additional missing values indicate the presence of corrupted or non-standard records within the dataset. They were subsequently handled during the data cleaning stage through appropriate imputation or removal strategies.

This step is essential because ensuring correct data types and identifying invalid entries improves the overall quality of the dataset and prevents errors during feature engineering and model training.


In [ ]:
###  Missing Values Summary

# After converting key variables to their correct data types, i  examined the dataset for missing values using:


customer_transaction_data.isnull().sum()


transaction_id                 0
customer_id                    0
timestamp                     61
home_country                   0
source_currency                0
dest_currency                  0
channel                        0
amount_src                     4
amount_usd                   305
fee                          295
exchange_rate_src_to_dest      0
device_id                      0
new_device                     0
ip_address                   305
ip_country                   301
location_mismatch              0
ip_risk_score                  0
kyc_tier                     300
account_age_days               0
device_trust_score           295
chargeback_history_count       0
risk_score_internal            0
txn_velocity_1h                0
txn_velocity_24h               0
corridor_risk                  0
is_fraud                       0
dtype: int64

This revealed the following counts of missing entries across the dataset:

timestamp: 61 missing

amount_src: 4 missing

amount_usd: 305 missing

fee: 295 missing

ip_address: 305 missing

device_trust_score: 295 missing

All other columns have complete data with 0 missing values

VARIABLES WITH MISSING VALUES THAT NEED IMPUTATION

amount_usd: has 305 missing values. This will be filled by multiplying amount_src by the exchange rate of the currency.

fee: has 295 missing values. These will be filled using the median fee of each channel (if channel exists). Any remaining missing fee values will be filled using the overall median.

ip_country: has 301 missing values. These will be filled using the corresponding home_country.

kyc_tier: has 300 missing values. These will be filled using the most frequent kyc_tier (mode).

device_trust_score: has 295 missing values. These will be filled using the median device_trust_score grouped by kyc_tier and new_device. Remaining missing values will be filled using the overall median.

timestamp: has 61 missing values. These rows will be dropped because the missing proportion is very small.

amount_src: has 4 missing values. These rows will be dropped because the missing proportion is very small.

ip_address: has 305 missing values. These cannot be imputed because each IP address is unique. Rows with missing ip_address will be dropped.

In [ ]:
#calculating exchange rates per currency
exchange_rates = customer_transaction_data[customer_transaction_data['amount_usd'].notna()].groupby('source_currency').apply(
    lambda x: (x['amount_usd'] / x['amount_src']).mean()
).to_dict()
exchange_rates


C:\Users\user\AppData\Local\Temp\ipykernel_9676\562282108.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  exchange_rates = customer_transaction_data[customer_transaction_data['amount_usd'].notna()].groupby('source_currency').apply(


{'CAD': 0.7216095926871465,
 'GBP': 1.223441221648679,
 'USD': 0.9838730321259439}

In [ ]:
#filling the missing values of the amount_usd
customer_transaction_data['amount_usd'] = customer_transaction_data.apply(
    lambda row: row['amount_usd'] if pd.notna(row['amount_usd']) else row['amount_src'] * exchange_rates.get(row['source_currency'], 1),
    axis=1
)


In [ ]:
missing_df = pd.DataFrame({
    'Column Name': customer_transaction_data.columns,
    'Missing Count': customer_transaction_data.isna().sum(),
    'Missing Pct': customer_transaction_data.isna().mean() * 100
})

missing_df


,Column Name,Missing Count,Missing Pct
transaction_id,transaction_id,0,0.000000
customer_id,customer_id,0,0.000000
timestamp,timestamp,61,0.535088
home_country,home_country,0,0.000000
source_currency,source_currency,0,0.000000
dest_currency,dest_currency,0,0.000000
channel,channel,0,0.000000
amount_src,amount_src,4,0.035088
amount_usd,amount_usd,0,0.000000
fee,fee,295,2.587719


In [ ]:
# filling the missing values of the fee variable
if 'fee' in customer_transaction_data.columns:
    if 'channel' in customer_transaction_data.columns:
        customer_transaction_data['fee'] = customer_transaction_data.groupby('channel')['fee'].transform(lambda y: y.fillna(y.median()))
    customer_transaction_data['fee'] = customer_transaction_data['fee'].fillna(customer_transaction_data['fee'].median())


In [ ]:
# filling the missing values of ip_country variable
if {'ip_country', 'home_country'}.issubset(customer_transaction_data.columns):
    customer_transaction_data['ip_country'] = customer_transaction_data['ip_country'].fillna(customer_transaction_data['home_country'])


In [ ]:
# filling the missing values of ip_country variable
if {'ip_country', 'home_country'}.issubset(customer_transaction_data.columns):
    customer_transaction_data['ip_country'] = customer_transaction_data['ip_country'].fillna(customer_transaction_data['home_country'])


In [ ]:
# filling the missing values of device_trust_score variable
if 'device_trust_score' in customer_transaction_data.columns:
    if {'new_device', 'kyc_tier'}.issubset(customer_transaction_data.columns):
        customer_transaction_data['device_trust_score'] = customer_transaction_data.groupby(['new_device', 'kyc_tier'])['device_trust_score'].transform(lambda x: x.fillna(x.mean()))
    customer_transaction_data['device_trust_score'] = customer_transaction_data['device_trust_score'].fillna(customer_transaction_data['device_trust_score'].mean())


In [ ]:
# dropping the timestamp, amount_src and ip_address missing values
customer_transaction_data.dropna(subset=['timestamp', 'amount_src', 'ip_address'], inplace=True)


In [ ]:
# rechecking for missing values
customer_transaction_data.isnull().sum()


transaction_id               0
customer_id                  0
timestamp                    0
home_country                 0
source_currency              0
dest_currency                0
channel                      0
amount_src                   0
amount_usd                   0
fee                          0
exchange_rate_src_to_dest    0
device_id                    0
new_device                   0
ip_address                   0
ip_country                   0
location_mismatch            0
ip_risk_score                0
kyc_tier                     0
account_age_days             0
device_trust_score           0
chargeback_history_count     0
risk_score_internal          0
txn_velocity_1h              0
txn_velocity_24h             0
corridor_risk                0
is_fraud                     0
dtype: int64

STEPS TO TAKE TO DO THE SANITY CHECK
• Check for invalid numbers i.e negative numbers for variables that contains age, monetary values, velocity etc
• Check if transaction timestamp appear in the future
• Check that values falls between range
• Inspect for inconsistency among variable values in the dataset


In [ ]:
# Checking negative values in numeric columns
negative_counts = {
    'amount_src': (customer_transaction_data['amount_src'] < 0).sum(),
    'amount_usd': (customer_transaction_data['amount_usd'] < 0).sum(),
    'fee': (customer_transaction_data['fee'] < 0).sum(),
    'device_trust_score': (customer_transaction_data['device_trust_score'] < 0).sum(),
    'txn_velocity_1h': (customer_transaction_data['txn_velocity_1h'] < 0).sum(),
    'risk_score_internal': (customer_transaction_data['risk_score_internal'] < 0).sum(),
}
negative_counts


{'amount_src': np.int64(100),
 'amount_usd': np.int64(0),
 'fee': np.int64(90),
 'device_trust_score': np.int64(190),
 'txn_velocity_1h': np.int64(190),
 'risk_score_internal': np.int64(0)}

In [ ]:
customer_transaction_data = customer_transaction_data.drop(customer_transaction_data[
    (customer_transaction_data['amount_src'] < 0) |
    (customer_transaction_data['device_trust_score'] < 0) |
    (customer_transaction_data['txn_velocity_1h'] < 0)
].index)


In [ ]:
# Rechecking for negative numbers again
negative_counts = {
    'amount_src': (customer_transaction_data['amount_src'] < 0).sum(),
    'amount_usd': (customer_transaction_data['amount_usd'] < 0).sum()
}


In [ ]:
# Checking negative values in numeric columns
negative_counts = {
    'amount_src': (customer_transaction_data['amount_src'] < 0).sum(),
    'amount_usd': (customer_transaction_data['amount_usd'] < 0).sum(),
    'fee': (customer_transaction_data['fee'] < 0).sum(),
    'device_trust_score': (customer_transaction_data['device_trust_score'] < 0).sum(),
    'txn_velocity_1h': (customer_transaction_data['txn_velocity_1h'] < 0).sum(),
    'risk_score_internal': (customer_transaction_data['risk_score_internal'] < 0).sum(),
}
negative_counts

{'amount_src': np.int64(0),
 'amount_usd': np.int64(0),
 'fee': np.int64(0),
 'device_trust_score': np.int64(0),
 'txn_velocity_1h': np.int64(0),
 'risk_score_internal': np.int64(0)}

In [ ]:
# checking for futuristic timestamp
customer_transaction_data[customer_transaction_data['timestamp'] > pd.Timestamp.utcnow()]


,transaction_id,customer_id,timestamp,home_country,source_currency,dest_currency,channel,amount_src,amount_usd,fee,...,ip_risk_score,kyc_tier,account_age_days,device_trust_score,chargeback_history_count,risk_score_internal,txn_velocity_1h,txn_velocity_24h,corridor_risk,is_fraud


In [ ]:
# checking for location mismatch
customer_transaction_data['location_mismatch'].value_counts().reset_index()


,location_mismatch,count
0,False,9047
1,True,1793


In [ ]:
# reviewing the channel variable
customer_transaction_data['channel'].unique()


array(['ATM', 'web', 'mobile', 'WEB', ' web  ', 'MOBILE', 'unknown',
       'mobille', ' mobile  ', 'weeb', 'ATm', ' ATM  '], dtype=object)

In [ ]:
# cleaning the channel variable
customer_transaction_data['channel'] = customer_transaction_data['channel'].str.lower().str.strip()
customer_transaction_data['channel'].unique()


array(['atm', 'web', 'mobile', 'unknown', 'mobille', 'weeb'], dtype=object)

In [ ]:
customer_transaction_data['channel'] = customer_transaction_data['channel'].replace({
    'weeb':'web',
    'mobile':'mobile',
})


In [ ]:
customer_transaction_data['channel'] = customer_transaction_data['channel'].replace({'unknown':np.nan})
customer_transaction_data['channel'].unique()


array(['atm', 'web', 'mobile', nan, 'mobille'], dtype=object)

In [ ]:
# reviewing the source currency variable
customer_transaction_data['source_currency'].unique()


array(['USD', 'CAD', 'GBP'], dtype=object)

In [ ]:
# reviewing the destination currency variable
customer_transaction_data['dest_currency'].unique()


array(['CAD', 'MXN', 'CNY', 'EUR', 'INR', 'GBP', 'PHP', 'NGN', 'USD'],
      dtype=object)

In [ ]:
customer_transaction_data['home_country_norm'] = (
    customer_transaction_data['home_country'].apply(normalize_country)
)


In [ ]:
customer_transaction_data['ip_country_norm'] = (
    customer_transaction_data['ip_country'].apply(normalize_country)
)

In [7]:
import pandas as pd

cleaned_customer_transaction_data = pd.read_csv('../Finlora_Dataset/FinLora_Customer_Transaction_Dataset.csv')

cleaned_customer_transaction_data.head()
cleaned_customer_transaction_data.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11400 entries, 0 to 11399
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   transaction_id             11400 non-null  object 
 1   customer_id                11400 non-null  object 
 2   timestamp                  11371 non-null  object 
 3   home_country               11400 non-null  object 
 4   source_currency            11400 non-null  object 
 5   dest_currency              11400 non-null  object 
 6   channel                    11400 non-null  object 
 7   amount_src                 11400 non-null  object 
 8   amount_usd                 11095 non-null  float64
 9   fee                        11105 non-null  float64
 10  exchange_rate_src_to_dest  11400 non-null  float64
 11  device_id                  11400 non-null  object 
 12  new_device                 11400 non-null  bool   
 13  ip_address                 11095 non-null  obj

In [8]:
# --- Normalize home_country ---

# Clean formatting
cleaned_customer_transaction_data['home_country'] = (
    cleaned_customer_transaction_data['home_country']
    .astype(str)
    .str.strip()
    .str.upper()
)

# Map ISO codes and variations to full names
home_country_map = {
    'UK': 'UNITED KINGDOM',
    'U.K.': 'UNITED KINGDOM',
    'GB': 'UNITED KINGDOM',
    'KE': 'KENYA',
    'US': 'UNITED STATES',
    'USA': 'UNITED STATES'
}

cleaned_customer_transaction_data['home_country'] = (
    cleaned_customer_transaction_data['home_country']
    .replace(home_country_map)
)


In [9]:
# --- Normalize ip_country ---

cleaned_customer_transaction_data['ip_country'] = (
    cleaned_customer_transaction_data['ip_country']
    .astype(str)
    .str.strip()
    .str.upper()
)

ip_country_map = {
    'UK': 'UNITED KINGDOM',
    'U.K.': 'UNITED KINGDOM',
    'GB': 'UNITED KINGDOM',
    'KE': 'KENYA',
    'US': 'UNITED STATES',
    'USA': 'UNITED STATES'
}

cleaned_customer_transaction_data['ip_country'] = (
    cleaned_customer_transaction_data['ip_country']
    .replace(ip_country_map)
)

# Fill missing ip_country using home_country
cleaned_customer_transaction_data['ip_country'] = (
    cleaned_customer_transaction_data['ip_country']
    .fillna(cleaned_customer_transaction_data['home_country'])
)


In [10]:
# --- Normalize kyc_tier ---

cleaned_customer_transaction_data['kyc_tier'] = (
    cleaned_customer_transaction_data['kyc_tier']
    .astype(str)
    .str.strip()
    .str.lower()
)

kyc_map = {
    'tier1': 'Tier 1',
    'tier 1': 'Tier 1',
    't1': 'Tier 1',
    'basic': 'Tier 1',

    'tier2': 'Tier 2',
    'tier 2': 'Tier 2',
    't2': 'Tier 2',
    'standard': 'Tier 2',

    'tier3': 'Tier 3',
    'tier 3': 'Tier 3',
    't3': 'Tier 3',
    'enhanced': 'Tier 3'
}

cleaned_customer_transaction_data['kyc_tier'] = (
    cleaned_customer_transaction_data['kyc_tier']
    .replace(kyc_map)
)

# Fill missing with mode
cleaned_customer_transaction_data['kyc_tier'] = (
    cleaned_customer_transaction_data['kyc_tier']
    .fillna(cleaned_customer_transaction_data['kyc_tier'].mode()[0])
)

cleaned_customer_transaction_data['kyc_tier'] = cleaned_customer_transaction_data['kyc_tier'].astype('category')


Fraud Feature — Country Mismatch- 

In [11]:
cleaned_customer_transaction_data['country_mismatch'] = (
    cleaned_customer_transaction_data['home_country'] != cleaned_customer_transaction_data['ip_country']
).astype(int)


In [12]:
cleaned_customer_transaction_data['home_country'] != cleaned_customer_transaction_data['ip_country']


0        False
1        False
2        False
3        False
4        False
         ...  
11395    False
11396     True
11397     True
11398    False
11399    False
Length: 11400, dtype: bool

What the feature does
The feature compares:

home_country → where the customer is registered

ip_country → where the transaction originated from (based on IP address)

If they are different, we mark the transaction as 1 (mismatch).
If they are the same, we mark it as 0 (no mismatch).

Why I used it-I created the country_mismatch feature because location inconsistency is a well‑known fraud indicator.
It helps the fraud detection model identify:

suspicious login locations

abnormal transaction origins

potential account compromise

high‑risk cross‑border behaviour